source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'API-Request' do

pod 'Alamofire', '~> 1.2'
pod 'SwiftyJSON', '~> 2.2.0'

end

target 'API-RequestTests' do

end

